#!/usr/bin/env python
import trio
import trio_asyncio

import argparse
import asyncio
import os.path
import time

import smokesignal
from syncrypt.app import SyncryptDaemonApp
from syncrypt.config import AppConfig
from syncrypt.utils.daemon import Daemon
from syncrypt.utils.logging import setup_logging

try:
    import win_unicode_console; win_unicode_console.enable()
except ImportError:
    pass

# Register builtins
#import syncrypt.builtins.chaos_monkey
import syncrypt.builtins.log

LOGLEVELS = ['CRITICAL', 'ERROR', 'WARN', 'INFO', 'DEBUG']

parser = argparse.ArgumentParser(description='Run Syncrypt client')
parser.add_argument('-d,--detach', action='store_true',
        dest='detach', help='Detach from console')
parser.add_argument('-c,--config', action='store', type=str,
        dest='config', help='Config file')
parser.add_argument('-I,--inspector', action='store_true',
        dest='inspector', help='Run Trio Inspector')
parser.add_argument('--no-initial-push', action='store_false',
        dest='initial_push', help='Do not push all vaults after daemon started')
parser.add_argument('-l', metavar='LOGLEVEL', type=str, default='INFO',
        dest='loglevel', choices=LOGLEVELS, help='Log level: ' + ', '.join(LOGLEVELS))

config = parser.parse_args()

app_config = AppConfig(config.config)

# setup logging
log_dir = os.path.join(app_config.config_dir, 'logs')
os.makedirs(log_dir, exist_ok=True)
setup_logging(config.loglevel, logfile=os.path.join(log_dir, 'syncrypt_daemon.log'))


async def run_syncrypt():
    async with trio.open_nursery() as nursery:
        if config.inspector:
            from trio_inspector import TrioInspector
            nursery.start_soon(TrioInspector().run)

        app = SyncryptDaemonApp(app_config,
                nursery=nursery,
                initial_push=config.initial_push
        )

        smokesignal.emit('pre_setup', app=app)

        await app.start()
        await app.initialize()

        smokesignal.emit('post_setup', app=app)

        nursery.start_soon(app.post_setup)

        await trio.sleep(100)

        #try:
        #    loop.run_until_complete(app.wait_for_shutdown())
        #except KeyboardInterrupt:
        #    pass

        smokesignal.emit('shutdown', app=app)

        return app.restart_flag


if config.detach:
    class SyncryptDaemon(Daemon):
        def run(self):
            while trio.run(run_syncrypt):
                time.sleep(2)
    syncryptd = SyncryptDaemon('/tmp/syncrypt.pid')
    getattr(syncryptd, config.command)()
else:
    while trio_asyncio.run(run_syncrypt):
        time.sleep(2)

